--- #YAML:1.0
name:               WWW-Shorten-MahewinSexyUrl
version:            0.2
abstract:           Perl interface to msud.pl
author:
    - Natal Ngétal <hobbestig@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:    0
    WWW::Shorten:  3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
